"""added a rarity column in the reward model

Revision ID: 1325bed56a31
Revises: 929642f3ab91
Create Date: 2025-07-31 22:02:33.044564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1325bed56a31"
down_revision: Union[str, None] = "929642f3ab91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reward",
        sa.Column(
            "rarity",
            sa.Enum("COMMON", "RARE", "EPIC", "LEGENDARY", name="rewardrarity"),
            nullable=False,
            server_default=sa.text("'COMMON'"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reward", "rarity")
    # ### end Alembic commands ###
