"""renamed study_session column into base_xp instead of xp_earned

Revision ID: 145f56c89b8a
Revises: 50a143065113
Create Date: 2025-07-18 16:27:01.853282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "145f56c89b8a"
down_revision: Union[str, None] = "50a143065113"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("studysession", "xp_earned", new_column_name="base_xp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column("studysession", "base_xp", new_column_name="xp_earned")
