"""added next_level_xp to the player model

Revision ID: 1474d0ee632b
Revises: 1210686e697f
Create Date: 2025-07-17 22:58:13.670877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1474d0ee632b"
down_revision: Union[str, None] = "1210686e697f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1️⃣ Add the column as nullable first
    op.add_column("player", sa.Column("next_level_xp", sa.Integer(), nullable=True))

    # 2️⃣ Fill existing rows with the default value
    op.execute("UPDATE player SET next_level_xp = 195")

    # 3️⃣ Alter the column to be NOT NULL
    op.alter_column("player", "next_level_xp", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "next_level_xp")
    # ### end Alembic commands ###
