"""added bonus xp in study session and added session and daily streak on the player as well as their longest ones

Revision ID: 50a143065113
Revises: 1474d0ee632b
Create Date: 2025-07-18 16:18:31.419213

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50a143065113"
down_revision: Union[str, None] = "1474d0ee632b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "session_streak", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "player",
        sa.Column(
            "longest_session_streak",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "player",
        sa.Column(
            "daily_streak", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "player",
        sa.Column(
            "longest_daily_streak",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "studysession",
        sa.Column(
            "bonus_xp", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studysession", "bonus_xp")
    op.drop_column("player", "longest_daily_streak")
    op.drop_column("player", "daily_streak")
    op.drop_column("player", "longest_session_streak")
    op.drop_column("player", "session_streak")
    # ### end Alembic commands ###
