"""changed the relation to player weekly checkins instead of user to weekly checkins

Revision ID: 6995b9b6beb3
Revises: aebd33eb1156
Create Date: 2025-07-22 20:52:38.271224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6995b9b6beb3"
down_revision: Union[str, None] = "aebd33eb1156"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("weeklycheckin", sa.Column("player_id", sa.Integer(), nullable=False))
    op.drop_index("ix_weeklycheckin_user_id", table_name="weeklycheckin")
    op.create_index(
        op.f("ix_weeklycheckin_player_id"), "weeklycheckin", ["player_id"], unique=False
    )
    op.drop_constraint(
        "fk_weekly_checkin_user_id_user", "weeklycheckin", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "weeklycheckin", "player", ["player_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("weeklycheckin", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weeklycheckin",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "weeklycheckin", type_="foreignkey")
    op.create_foreign_key(
        "weeklycheckin_user_id_fkey",
        "weeklycheckin",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_weeklycheckin_player_id"), table_name="weeklycheckin")
    op.create_index(
        "ix_weeklycheckin_user_id", "weeklycheckin", ["user_id"], unique=False
    )
    op.drop_column("weeklycheckin", "player_id")
    # ### end Alembic commands ###
