"""new column in reward model for equipped image url

Revision ID: 761131a5b9c8
Revises: d2ed19b3e228
Create Date: 2025-07-29 22:12:26.378168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "761131a5b9c8"
down_revision: Union[str, None] = "d2ed19b3e228"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reward", sa.Column("equipped_image_url", sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reward", "equipped_image_url")
    # ### end Alembic commands ###
