"""added boss_streak_counter column in the player model

Revision ID: 8159aebd9a8c
Revises: 2f23ce3cd4a9
Create Date: 2025-07-27 17:29:04.629058

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8159aebd9a8c"
down_revision: Union[str, None] = "2f23ce3cd4a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("playerbossstatus")
    op.add_column(
        "player",
        sa.Column(
            "boss_streak_counter",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),  # Use sa.text("0") for database literal
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "boss_streak_counter")
    op.create_table(
        "playerbossstatus",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("player_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "available_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "defeated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
            name="playerbossstatus_player_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="playerbossstatus_pkey"),
    )
    # ### end Alembic commands ###
