"""new column in reward model for description of the reward

Revision ID: 8837cb4a82a0
Revises: a6ad66000032
Create Date: 2025-07-29 22:18:19.326798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8837cb4a82a0"
down_revision: Union[str, None] = "a6ad66000032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reward", sa.Column("description", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reward", "description")
    # ### end Alembic commands ###
