"""renamed a column  in reward model from equiped to equipped  image url

Revision ID: a6ad66000032
Revises: 761131a5b9c8
Create Date: 2025-07-29 22:15:06.233222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6ad66000032"
down_revision: Union[str, None] = "761131a5b9c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reward", sa.Column("equipped_image_url", sa.VARCHAR(), nullable=True)
    )
    op.drop_column("reward", "equiped_image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reward",
        sa.Column(
            "equiped_image_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("reward", "equipped_image_url")
    # ### end Alembic commands ###
