"""renamed the boss_streak_counter column to boss_availability_counter in the player model

Revision ID: d9b7a35967c1
Revises: 8159aebd9a8c
Create Date: 2025-07-27 17:35:56.150359

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9b7a35967c1"
down_revision: Union[str, None] = "8159aebd9a8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "boss_availability_counter",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.drop_column("player", "boss_streak_counter")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "boss_streak_counter",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("player", "boss_availability_counter")
    # ### end Alembic commands ###
